version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      -run:
          name: php-cs-fix-v2
          command: echo PHP-FIX
      - run:
          name: Print the Current Time
          command: date
